import { useState } from 'react';
import { AdminShell } from '@/pages/AdminDashboardPage';

const initialReviews = [
  { id: 1, name: 'Daniel K.', profile: 'Zahara J.', rating: 5, text: 'A wonderful experience from start to finish. Professional, warm, and exactly as described.', date: 'Today, 09:42', status: 'Published' },
  { id: 2, name: 'Michael R.', profile: 'Maya Entebbe', rating: 2, text: 'This review has been flagged by the community for inappropriate language and needs attention.', date: 'Yesterday, 16:20', status: 'Flagged' },
  { id: 3, name: 'Alex T.', profile: 'Nora Divine', rating: 4, text: 'Very easy to communicate with and the profile was accurate. Would recommend.', date: 'Jun 12, 2024', status: 'Published' },
  { id: 4, name: 'Chris M.', profile: 'Bella Rose', rating: 1, text: 'A reported review awaiting moderation before it is visible publicly.', date: 'Jun 11, 2024', status: 'Pending' },
];

export function AdminReviewsPage() {
  const [reviews, setReviews] = useState(initialReviews);
  const [filter, setFilter] = useState('All');
  const visible = reviews.filter((review) => filter === 'All' || review.status === filter);
  const updateStatus = (id: number, status: string) => setReviews((items) => items.map((item) => item.id === id ? { ...item, status } : item));
  return <AdminShell activeRoute="admin-reviews" title="Reviews" badge="12 FLAGGED"><div className="mx-auto max-w-5xl space-y-6 p-6 lg:p-8"><div><p className="text-sm text-on-surface-variant">Keep community feedback helpful, accurate, and respectful.</p><h1 className="mt-2 font-display text-3xl text-on-surface">Review Moderation</h1></div><div className="flex flex-wrap gap-2">{['All', 'Flagged', 'Pending', 'Published'].map((item) => <button key={item} onClick={() => setFilter(item)} className={'rounded-full px-4 py-2 text-xs font-bold ' + (filter === item ? 'bg-secondary text-on-secondary' : 'bg-surface-container text-on-surface-variant')}>{item}</button>)}</div><div className="space-y-4">{visible.map((review) => <article key={review.id} className="rounded-2xl bg-surface-container p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex flex-wrap items-center gap-3"><h2 className="font-bold text-on-surface">{review.name}</h2><span className="text-xs text-on-surface-variant">reviewed {review.profile}</span><span className={'rounded px-2 py-1 text-[10px] font-bold ' + (review.status === 'Flagged' ? 'bg-primary/15 text-primary' : review.status === 'Pending' ? 'bg-secondary/15 text-secondary' : 'bg-green-500/15 text-green-400')}>{review.status}</span></div><div className="mt-3 flex gap-1 text-secondary">{Array.from({ length: 5 }).map((_, i) => <span key={i} className="material-symbols-outlined fill text-base">{i < review.rating ? 'star' : 'star_border'}</span>)}</div></div><span className="text-xs text-on-surface-variant">{review.date}</span></div><p className="mt-4 max-w-3xl text-sm leading-relaxed text-on-surface-variant">{review.text}</p><div className="mt-5 flex flex-wrap gap-2">{review.status !== 'Published' && <button onClick={() => updateStatus(review.id, 'Published')} className="rounded-lg bg-green-500/15 px-4 py-2 text-xs font-bold text-green-400 hover:bg-green-500/25">Publish</button>}{review.status !== 'Flagged' && <button onClick={() => updateStatus(review.id, 'Flagged')} className="rounded-lg bg-primary/10 px-4 py-2 text-xs font-bold text-primary hover:bg-primary/20">Flag</button>}<button onClick={() => setReviews((items) => items.filter((item) => item.id !== review.id))} className="rounded-lg bg-surface-container-high px-4 py-2 text-xs font-bold text-on-surface-variant hover:text-error">Remove</button></div></article>)}</div></div></AdminShell>;
}
